AWSTemplateFormatVersion: "2010-09-09"
#
# otlp2pipeline - AWS S3 Tables + Firehose for OTLP logs
#
# Based on: https://github.com/chariotsolutions/aws-examples/blob/bb15866e20a5556775590c95ee27bdf54f7dd550/cloudtrail_firehose/firehose-s3table.yml
#
# Creates a Firehose stream that delivers OTLP log data to an S3 Table (Iceberg format).
#
# Before running the template, make sure "Integration with AWS analytics services" is enabled on the S3 Tables UI.
#
# This template must be run in two phases:
#
# Phase 1: Deploy with Phase=1 to create all resources except Firehose
# Phase 2: Grant LakeFormation permissions to the Firehose role, then deploy with Phase=2
#
# To work-around CloudFormation limitations with LakeFormation:
# - Apply the template with Phase=1
# - Go into LakeFormation and attach permissions to the created Firehose Role:
#   - DESCRIBE on s3tablescatalog and s3tablescatalog/{TableBucketName}
#   - ALL (Super) on the logs table
# - Re-apply the template with Phase=2
#
# See: https://docs.aws.amazon.com/AmazonS3/latest/userguide/grant-permissions-tables.html
#
Description: >
  Creates an S3 Table Bucket, Namespace, and Iceberg Table for OTLP logs,
  along with a Kinesis Firehose (DirectPut) to populate it with JSON records.

Parameters:
  Phase:
    Description: >
      Phase 1 creates all resources except Firehose.
      Phase 2 creates Firehose after LakeFormation permissions are granted manually.
    Type: String
    AllowedValues: ["1", "2"]
    Default: "1"

  TableBucketName:
    Description: Name of the S3 Table Bucket
    Type: String
    Default: otlp2pipeline

  NamespaceName:
    Description: Name of the S3 Table Namespace
    Type: String
    Default: default

  TableName:
    Description: Name of the S3 Table
    Type: String
    Default: logs

  PrimaryKey:
    Description: Name of the primary key column
    Type: String
    Default: timestamp

  FirehoseErrorPrefix:
    Description: Prefix in error bucket (must include trailing slash)
    Type: String
    Default: firehose_errors/

  FirehoseBatchTime:
    Description: Firehose buffering interval (seconds)
    Type: Number
    MinValue: 60
    MaxValue: 900
    Default: 120

  FirehoseBatchSize:
    Description: Firehose buffering size (MB)
    Type: Number
    MinValue: 1
    MaxValue: 128
    Default: 32

Conditions:
  CreateFirehose: !Equals [!Ref Phase, "2"]

Resources:
  ############################################################
  # S3 Tables resources
  ############################################################
  FirehoseErrorBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub ${AWS::StackName}-firehose-errors-${AWS::AccountId}-${AWS::Region}

  TableBucket:
    Type: AWS::S3Tables::TableBucket
    Properties:
      TableBucketName: !Ref TableBucketName
      EncryptionConfiguration:
        SSEAlgorithm: AES256
      UnreferencedFileRemoval:
        Status: Enabled
        UnreferencedDays: 1
        NoncurrentDays: 1

  Namespace:
    Type: AWS::S3Tables::Namespace
    Properties:
      Namespace: !Ref NamespaceName
      TableBucketARN: !GetAtt TableBucket.TableBucketARN

  Table:
    Type: AWS::S3Tables::Table
    DependsOn: Namespace
    Properties:
      TableName: !Ref TableName
      TableBucketARN: !GetAtt TableBucket.TableBucketARN
      Namespace: !Ref NamespaceName
      OpenTableFormat: ICEBERG
      Compaction:
        Status: enabled
        TargetFileSizeMB: 64
      SnapshotManagement:
        Status: enabled
        MaxSnapshotAgeHours: 24
        MinSnapshotsToKeep: 8
      IcebergMetadata:
        IcebergSchema:
          SchemaFieldList:
            # OTLP log fields (matches vrl/otlp_logs.vrl schema)
            - Name: timestamp
              Type: timestamp
              Required: true
            - Name: observed_timestamp
              Type: long
              Required: true
            - Name: trace_id
              Type: string
              Required: false
            - Name: span_id
              Type: string
              Required: false
            - Name: service_name
              Type: string
              Required: true
            - Name: service_namespace
              Type: string
              Required: false
            - Name: service_instance_id
              Type: string
              Required: false
            - Name: severity_number
              Type: int
              Required: true
            - Name: severity_text
              Type: string
              Required: true
            - Name: body
              Type: string
              Required: false
            - Name: resource_attributes
              Type: string
              Required: false
            - Name: scope_name
              Type: string
              Required: false
            - Name: scope_version
              Type: string
              Required: false
            - Name: scope_attributes
              Type: string
              Required: false
            - Name: log_attributes
              Type: string
              Required: false

  ############################################################
  # Logging
  ############################################################

  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/kinesisfirehose/${AWS::StackName}
      RetentionInDays: 1

  FirehoseDestLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: Destination_Errors

  ############################################################
  # Firehose IAM Role
  ############################################################

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-DeliveryStreamRole-${AWS::Region}
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Ref AWS::AccountId
      Policies:
        - PolicyName: GlueAndLakeFormation
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - glue:GetTable
                  - glue:GetDatabase
                  - glue:UpdateTable
                Resource:
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog/s3tablescatalog
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog/s3tablescatalog/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/*
                  - !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/*/*

              - Effect: Allow
                Action:
                  - lakeformation:GetDataAccess
                Resource: "*"

        - PolicyName: LoggingAndErrors
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:Describe*
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FirehoseLogGroup}
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FirehoseLogGroup}:*

              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                Resource:
                  - !Sub arn:aws:s3:::${FirehoseErrorBucket}

              - Effect: Allow
                Action:
                  - s3:AbortMultipartUpload
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${FirehoseErrorBucket}/${FirehoseErrorPrefix}${TableName}/*

  ############################################################
  # Firehose (created only in Phase 2)
  ############################################################

  Firehose:
    Type: AWS::KinesisFirehose::DeliveryStream
    Condition: CreateFirehose
    Properties:
      DeliveryStreamName: !Ref AWS::StackName
      DeliveryStreamType: DirectPut

      IcebergDestinationConfiguration:
        RoleARN: !GetAtt FirehoseRole.Arn

        CatalogConfiguration:
          CatalogArn: !Sub arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog/s3tablescatalog/${TableBucketName}

        DestinationTableConfigurationList:
          - DestinationDatabaseName: !Ref NamespaceName
            DestinationTableName: !Ref TableName
            UniqueKeys:
              - !Ref PrimaryKey

        BufferingHints:
          IntervalInSeconds: !Ref FirehoseBatchTime
          SizeInMBs: !Ref FirehoseBatchSize

        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: !Ref FirehoseDestLogStream

        S3Configuration:
          RoleARN: !GetAtt FirehoseRole.Arn
          BucketARN: !Sub arn:aws:s3:::${FirehoseErrorBucket}
          ErrorOutputPrefix: !Sub ${FirehoseErrorPrefix}${TableName}/

Outputs:
  TableBucketARN:
    Description: ARN of the S3 Table Bucket
    Value: !GetAtt TableBucket.TableBucketARN

  FirehoseRoleARN:
    Description: ARN of the Firehose IAM Role (grant LakeFormation permissions to this role)
    Value: !GetAtt FirehoseRole.Arn

  FirehoseRoleName:
    Description: Name of the Firehose IAM Role
    Value: !Ref FirehoseRole

  FirehoseDeliveryStreamName:
    Condition: CreateFirehose
    Description: Name of the Firehose Delivery Stream
    Value: !Ref Firehose

  FirehoseDeliveryStreamARN:
    Condition: CreateFirehose
    Description: ARN of the Firehose Delivery Stream
    Value: !GetAtt Firehose.Arn
